import { SAMPLE_SIZE } from "@/app/game";
import { Level } from "@/utils/rules";
import { sampleSize } from "lodash";

const COUNTRIES = [
  "Fiji",
  "Tanzania",
  "W. Sahara",
  "Canada",
  "United States of America",
  "Kazakhstan",
  "Uzbekistan",
  "Papua New Guinea",
  "Indonesia",
  "Argentina",
  "Chile",
  "Dem. Rep. Congo",
  "Somalia",
  "Kenya",
  "Sudan",
  "Chad",
  "Haiti",
  "Dominican Rep.",
  "Russia",
  "Bahamas",
  "Falkland Is.",
  "Norway",
  "Greenland",
  "Fr. S. Antarctic Lands",
  "Timor-Leste",
  "South Africa",
  "Lesotho",
  "Mexico",
  "Uruguay",
  "Brazil",
  "Bolivia",
  "Peru",
  "Colombia",
  "Panama",
  "Costa Rica",
  "Nicaragua",
  "Honduras",
  "El Salvador",
  "Guatemala",
  "Belize",
  "Venezuela",
  "Guyana",
  "Suriname",
  "France",
  "Ecuador",
  "Puerto Rico",
  "Jamaica",
  "Cuba",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "Senegal",
  "Mali",
  "Mauritania",
  "Benin",
  "Niger",
  "Nigeria",
  "Cameroon",
  "Togo",
  "Ghana",
  "Côte d'Ivoire",
  "Guinea",
  "Guinea-Bissau",
  "Liberia",
  "Sierra Leone",
  "Burkina Faso",
  "Central African Rep.",
  "Congo",
  "Gabon",
  "Eq. Guinea",
  "Zambia",
  "Malawi",
  "Mozambique",
  "eSwatini",
  "Angola",
  "Burundi",
  "Israel",
  "Lebanon",
  "Madagascar",
  "Palestine",
  "Gambia",
  "Tunisia",
  "Algeria",
  "Jordan",
  "United Arab Emirates",
  "Qatar",
  "Kuwait",
  "Iraq",
  "Oman",
  "Vanuatu",
  "Cambodia",
  "Thailand",
  "Laos",
  "Myanmar",
  "Vietnam",
  "North Korea",
  "South Korea",
  "Mongolia",
  "India",
  "Bangladesh",
  "Bhutan",
  "Nepal",
  "Pakistan",
  "Afghanistan",
  "Tajikistan",
  "Kyrgyzstan",
  "Turkmenistan",
  "Iran",
  "Syria",
  "Armenia",
  "Sweden",
  "Belarus",
  "Ukraine",
  "Poland",
  "Austria",
  "Hungary",
  "Moldova",
  "Romania",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Germany",
  "Bulgaria",
  "Greece",
  "Turkey",
  "Albania",
  "Croatia",
  "Switzerland",
  "Luxembourg",
  "Belgium",
  "Netherlands",
  "Portugal",
  "Spain",
  "Ireland",
  "New Caledonia",
  "Solomon Is.",
  "New Zealand",
  "Australia",
  "Sri Lanka",
  "China",
  "Taiwan",
  "Italy",
  "Denmark",
  "United Kingdom",
  "Iceland",
  "Azerbaijan",
  "Georgia",
  "Philippines",
  "Malaysia",
  "Brunei",
  "Slovenia",
  "Finland",
  "Slovakia",
  "Czechia",
  "Eritrea",
  "Japan",
  "Paraguay",
  "Yemen",
  "Saudi Arabia",
  "Antarctica",
  "N. Cyprus",
  "Cyprus",
  "Morocco",
  "Egypt",
  "Libya",
  "Ethiopia",
  "Djibouti",
  "Somaliland",
  "Uganda",
  "Rwanda",
  "Bosnia and Herz.",
  "North Macedonia",
  "Serbia",
  "Montenegro",
  "Kosovo",
  "Trinidad and Tobago",
  "S. Sudan",
];

const EASIEST_COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Australia",
  "China",
  "Japan",
  "Brazil",
  "Russia",
  "Mexico",
  "India",
  "South Africa",
  "Argentina",
  "Egypt",
  "Greece",
  "Thailand",
  "Turkey",
  "Sweden",
  "Norway",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Portugal",
  "Ireland",
  "New Zealand",
  "South Korea",
  "Saudi Arabia",
  "Israel",
  "Peru",
  "Colombia",
  "Kenya",
  "Indonesia",
  "Malaysia",
  "Vietnam",
  "Philippines",
  "Poland",
  "Australia",
];

export const getCountries = (level: Level) => {
  let countryPool: string[] = [];

  switch (level) {
    case Level.One:
      countryPool = EASIEST_COUNTRIES;
      break;
    default:
      countryPool = COUNTRIES;
      break;
  }

  const randomSample = sampleSize(countryPool, SAMPLE_SIZE);
  return randomSample;
};
